name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: temp set variable
      id: vars
      shell: pwsh
      run: echo "::set-output name=SOME_VAR::hello_world"

    - name: temp print variable
      shell: pwsh
      run: echo ${{ steps.vars.outputs.SOME_VAR }}

    - name: Checkout Git repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore NuGet packages
      run: dotnet restore src

    - name: Build
      run: dotnet build src --configuration Release --no-restore

    - name: Run unit tests
      id: unit_tests
      run: |
        dotnet test src --configuration Release --no-restore --verbosity normal --collect "XPlat Code Coverage"
        $coverage_file = Get-ChildItem -Path .\src -Filter coverage.cobertura.xml -Recurse | Select-Object -first 1
        echo "::set-output name=coverage_file::$coverage_file"

    - name: temp print variable 2
      shell: pwsh
      run: echo ${{ steps.unit_tests.outputs.coverage_file }}

    - name: Publish NuGet package as artifact
      uses: actions/upload-artifact@v2
      with:
        path: 'src/**/*.nupkg'
