name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore NuGet packages
      run: dotnet restore src

    - name: Build
      run: dotnet build src --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test src --configuration Release --no-restore --verbosity normal --collect "XPlat Code Coverage"

    - name: temp set variable
      run: echo ::set-env name=SOME_VAR::$(dir /B /S *coverage.cobertura.xml)

    - name: temp print variable
      run: echo ${{ env.SOME_VAR }}

    - name: Publish NuGet package as artifact
      uses: actions/upload-artifact@v2
      with:
        path: 'src/**/*.nupkg'
