name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    
    - name: Restore NuGet packages
      run: nuget restore src/CleanCodeHelper.sln
  
    - name: Build Solution
      run: msbuild src/CleanCodeHelper.sln /p:Configuration=Release

    - name: Execute Unit Tests
      run: dotnet test -l "console;verbosity=detailed" --collect "Code Coverage"

    - name: Upload NuGet package
      uses: actions/upload-artifact@v2
      with:
        path: 'src/**/*.nupkg'
